name: Build Artifact

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
      - ".github/**"
  pull_request:
    branches: [ master ]
  workflow_call:
    outputs:
      version: 
        description: "Version builded"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        #configuration: [Debug, Release]
        configuration: [Release]
        profile: [win, win-self]
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      SolutionName: RegexFileSorter.sln
      Configuration: ${{ matrix.configuration }}
      Profile: ${{ matrix.profile }}
    outputs:
      version: ${{steps.version.outputs.version}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Set VERSION
      id: version
      run: |
        dotnet tool install -g minver-cli --version 2.5.0
        $version = minver -t v -d preview
        $number = $version.Split('-')[0]
        echo "VERSION=$version"
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "::set-output name=version::$version"

    - name: Build solution
      run: dotnet build -c $env:Configuration
        
    - name: Build artifact
      #if: matrix.configuration == 'Release'
      run: dotnet publish -c Release -p:PublishProfile=$env:Profile /property:Version=$env:VERSION

    - name: Upload a Build Artifact
      #if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v2.3.1
      with:
        name: RegexFileSorter(${{ matrix.profile }})
        path: RegexFileSorterWF\bin\Release\net6.0-windows\publish\${{ matrix.profile }}\RegexFileSorterWF.exe
        if-no-files-found: error
